---
extends:
    - '@commitlint/config-conventional'
rules:
    header-max-length: [1, 'always', 100]
    type-enum:
        - 2
        - always
        - - chore
          - feat
          - fix
          - docs
          - refactor
          - test
help: |
    **Possible types**:
    `chore`:    Change build process, tooling or dependencies.
    `feat`:     Adds a new feature.
    `fix`:      Solves a bug.
    `docs`:     Adds or alters documentation.
    `refactor`: Rewrites code without feature, performance or bug changes.
    `test`:     Adds or modifies tests.
    `revert`:   Changes that reverting other changes
