# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:11

commands:
    bootstrap:
        description: 'Checkout and install dependencies'
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - jest-cache-v1-{{ arch }}
                      - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - run: yarn install
            - save_cache:
                  key: yarn-packages-v1-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
    version:
        description: 'Increment version and commit back'
        steps:
            - run:
                  name: Release
                  command: yarn release -m $npm_package_version [skip ci]
            - run:
                  name: Avoid hosts unknown for github
                  command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            - run:
                  name: Push
                  command: git push --follow-tags origin master
    release:
        description: 'Release new version'
        steps:
            - run:
                  name: Authenticate
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - deploy:
                  name: Publish
                  command: npm publish

jobs:
    build:
        <<: *defaults
        steps:
            - bootstrap
            - run:
                  name: Build
                  command: yarn build
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - .
    test:
        <<: *defaults
        steps:
            - bootstrap
            - run: yarn test:ci
            - save_cache:
                  key: jest-cache-v1-{{ arch }}
                  paths:
                      - test/.jest

    publish:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - version
            - release
workflows:
    version: 2
    default:
        jobs:
            - build
            - test
            - publish_approval:
                  type: approval
                  requires:
                      - build
                      - test
                  filters:
                      branches:
                          only: master
            - publish:
                  requires:
                      - publish_approval
