# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:11

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn install
            - save_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            - run:
                  name: Build
                  command: yarn build
            - persist_to_workspace:
                  root: ~/repo
                  paths: .
    test:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn install
            - save_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            - run:
                  name: Test
                  command: yarn test:ci
    publish:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Release
                  command: yarn release
            - run:
                  name: Avoid hosts unknown for github
                  command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            - run:
                  name: Push
                  command: git push --follow-tags origin master
            - run:
                  name: Authenticate
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish
                  command: npm publish
workflows:
    version: 2
    default:
        jobs:
            - build
            - test
            - publish_approval:
                  type: approval
                  requires:
                      - build
                      - test
            - publish:
                  requires:
                      - publish_approval
